version: '3.7'

services:
  
  service-registry:
    image: service-registry:latest
    build:
      dockerfile: ./service-registry/Dockerfile
    container_name: service-registry
    restart: always
    ports:
      - "8056:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    working_dir: /app
    command: [ "java", "-jar", "service-registry.jar" ]
    networks:
      - ups-grp6

  customer-service:
    image: customer-service:latest
    build:
      dockerfile: ./customer-service/Dockerfile
    container_name: customer-service
    restart: always
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      customer-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/api/v1/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    working_dir: /app
    command: [ "java", "-jar", "customer-service.jar" ]
    networks:
      - ups-grp6

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - ups-grp6
    depends_on:
      service-registry:
        condition: service_healthy
      customer-service:
        condition: service_healthy

  customer-db:
    image: postgres:15.8-bullseye
    container_name: customer-db
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=customer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d customer_db -U admin"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ups-grp6

volumes:
  pgdata:

networks:
  ups-grp6:
    name: ups-grp6