services:
  
  customer-service:
    image: customer-service:latest
    build:
      dockerfile: ./customer-service/Dockerfile
    container_name: customer-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      customer-db:
        condition: service_healthy      
    working_dir: /app
    command: [ "java", "-jar", "customer-service.jar" ]
    networks:
      - ups-grp6

  customer-db:
    image: postgres:15.8-bullseye
    container_name: customer-db
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=customer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d customer_db -U admin"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ups-grp6

volumes:
  pgdata:

networks:
  ups-grp6:
    name: ups-grp6
