spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      locator:
        enabled: true
      routes:
        - id: customer-service-route
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path= /api/v1/customers/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://<tenant_name>.auth0.com/
          audience: spring-boot-jwts
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8056/eureka/


